### ISSUE TITLE
`Parser::try_map` is hard to use

### ISSUE THREAD

**Issue by NobodyXu** [winnow-rs/winnow#294] opened 2023-07-22 04:34 UTC
### Please complete the following tasks

- [X] I have searched the [discussions](https://github.com/winnow-rs/winnow/discussions)
- [X] I have searched the [open](https://github.com/winnow-rs/winnow/issues) and [rejected](https://github.com/winnow-rs/winnow/issues?q=is%3Aissue+label%3AS-wont-fix+is%3Aclosed) issues

### rust version

rustc 1.71.0 (8ede3aae2 2023-07-12)

### winnow version

0.5.0

### Minimal reproducible code

```rust
use std::{marker::PhantomData, str};
use winnow::{
    ascii::digit1,
    error::{ContextError, PResult, ParserError},
    token::{tag, take_until0 as take_until},
    Parser,
};

fn terminated<I, O1, O2, E, F, G>(first: F, second: G) -> impl Parser<I, O1, E>
where
    F: Parser<I, O1, E>,
    G: Parser<I, O2, E>,
    E: ParserError<I>,
{
    struct P<F, G, O2> {
        first: F,
        second: G,
        phantom: PhantomData<O2>,
    }
    impl<I, O1, O2, E, F, G> Parser<I, O1, E> for P<F, G, O2>
    where
        F: Parser<I, O1, E>,
        G: Parser<I, O2, E>,
        E: ParserError<I>,
    {
        fn parse_next(&mut self, input: &mut I) -> PResult<O1, E> {
            let o1 = self.first.parse_next(input)?;
            self.second.parse_next(input)?;
            Ok(o1)
        }
    }

    P {
        first,
        second,
        phantom: PhantomData,
    }
}

fn parse_pax_item<'a>() -> impl Parser<&'a [u8], (&'a str, &'a str), ContextError> {
    (
        terminated(digit1, tag(" ")).try_map(str::from_utf8),
        terminated(take_until("="), tag("=")).try_map(str::from_utf8),
        terminated(take_until("\n"), tag("\n")).try_map(str::from_utf8),
    )
        .try_map(|(len_str, key, value)| {
            let msg_len = len_str.len() + key.len() + value.len() + 3;
            match len_str.parse::<usize>() {
                Ok(len_usize) if len_usize != msg_len => {
                    Err(format!("Invalid pax item: Expected {len_usize} bytes pax message, found {msg_len} bytes"))
                }
                Err(err) => {
                    Err(format!("Failed to parse pax message len: {err}"))
                }
                _ => Ok((key, value))
            }
        })
}
```

### Steps to reproduce the bug with the above code

```bash
cargo build
```

### Actual Behaviour

Failed to build because:

```
   Compiling s v0.1.0 (/private/tmp/s)
error[E0277]: the trait bound `TryMap<(TryMap<impl Parser<_, &[u8], _>, for<'b> fn(&'b [u8]) -> Result<&'b str, Utf8Error> {from_utf8}, _, &[u8], &str, _, Utf8Error>, TryMap<impl Parser<_, &[u8], _>, for<'b> fn(&'b [u8]) -> Result<&'b str, Utf8Error> {from_utf8}, _, &[u8], &str, _, Utf8Error>, TryMap<impl Parser<_, &[u8], _>, for<'b> fn(&'b [u8]) -> Result<&'b str, Utf8Error> {from_utf8}, _, &[u8], &str, _, Utf8Error>), [closure@src/lib.rs:46:18: 46:41], _, (&str, &str, &str), (&str, &str), _, String>: Parser<&'a [u8], (&'a str, &'a str), ContextError>` is not satisfied
  --> src/lib.rs:40:28
   |
40 | fn parse_pax_item<'a>() -> impl Parser<&'a [u8], (&'a str, &'a str), ContextError> {
   |                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `Parser<&'a [u8], (&'a str, &'a str), ContextError>` is not implemented for `TryMap<(TryMap<impl Parser<_, &[u8], _>, for<'a> fn(&'a [u8]) -> Result<&'a str, Utf8Error> {from_utf8}, _, &[u8], &str, _, Utf8Error>, TryMap<impl Parser<_, &[u8], _>, for<'a> fn(&'a [u8]) -> Result<&'a str, Utf8Error> {from_utf8}, _, &[u8], &str, _, Utf8Error>, TryMap<impl Parser<_, &[u8], _>, for<'a> fn(&'a [u8]) -> Result<&'a str, Utf8Error> {from_utf8}, _, &[u8], &str, _, Utf8Error>), [closure@src/lib.rs:46:18: 46:41], _, (&str, &str, &str), (&str, &str), _, String>`
   |
   = help: the trait `Parser<I, O2, E>` is implemented for `TryMap<F, G, I, O, O2, E, E2>`

For more information about this error, try `rustc --explain E0277`.
error: could not compile `s` (lib) due to previous error
```

### Expected Behaviour

It should just work.

**Comment by epage** [comment] 2023-07-22 15:04
With the error being that bad, I would assume the problem is with `Parser::try_map` having a looser bound than `impl Parser for TryMap` but they seem to be the same.

The only thing I can think of is that the outer `try_map` is using an error type that is not supported by [`impl FromExternalError for ContextError`](https://docs.rs/winnow/latest/winnow/error/struct.ContextError.html#impl-FromExternalError%3CI,+E%3E-for-ContextError%3CC%3E).

**Comment by NobodyXu** [comment] 2023-07-23 02:12
Thanks, I tried replacing `format!(...)` with a type that implements `error::Error` and it's fixed.

Although I do think the error message is extremely confusing.

**Comment by NobodyXu** [comment] 2023-07-23 02:55
I also wonder if winnow could have a "try_map_exact_error" which it accepts E as error type instead of "E2" where "E: FromExternalType<E2>"

**Comment by epage** [comment] 2023-07-24 20:08
> Although I do think the error message is extremely confusing.

Looking back over it, I'm not seeing anything I can do to improve the error message

As such, I'm going to unfortunately close this.

> I also wonder if winnow could have a "try_map_exact_error" which it accepts E as error type instead of "E2" where "E: FromExternalType"

If you want to discuss this further, I'd recommend a Discussion or dedicated issue.

What will be important to me is the use case for why this would be common enough to build in rather than doing this directly.  There are a lot of different potential considerations for error construction and covering them all would be overwhelming,

**Closed by epage** 2023-07-24 20:08 UTC
Labels: C-bug

**Comment by NobodyXu** [comment] 2023-07-25 02:02
> Looking back over it, I'm not seeing anything I can do to improve the error message

I think we could require E2 to implement std::error::Error?
That would make it clear where the error comes from.

> > I also wonder if winnow could have a "try_map_exact_error" which it accepts E as error type instead of "E2" where "E: FromExternalType"
> 
> If you want to discuss this further, I'd recommend a Discussion or dedicated issue.
> 
> What will be important to me is the use case for why this would be common enough to build in rather than doing this directly. There are a lot of different potential considerations for error construction and covering them all would be overwhelming,

Sure!

**Comment by epage** [comment] 2023-07-25 02:13
> I think we could require E2 to implement std::error::Error?
> That would make it clear where the error comes from.

iiuc the only reason `std::error::Error` is required in this case is because of the choice of `E`, so this is covered by the trait bound already, except the error is terrible.

I'd like to avoid forcing people to use `std::error::Error` here.

**Comment by NobodyXu** [comment] 2023-07-25 02:15
> > I think we could require E2 to implement std::error::Error?
> > That would make it clear where the error comes from.
> 
> iiuc the only reason `std::error::Error` is required in this case is because of the choice of `E`, so this is covered by the trait bound already, except the error is terrible.
> 
> I'd like to avoid forcing people to use `std::error::Error` here.

Understandable, though I do think implementator of `FromExternalError` usually requires `std::error::Error`.

Thanks for the quick reply!
